apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-test
  name: my-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-test
    spec:
      containers:
      - image: postgress
        name: postgress
        resources: {}
status: {}
